easy_admin:
    entities:
        Produit:
            class: App\Entity\Produit
            form:
                fields:
                    - {property: 'id'}
                    - {property: 'nom'}
                    - {property: 'prix'}
                    - {property: 'description'}
                    - {property: 'image'}
                    