vich_uploader:
    db_driver: orm
    mappings:
        avatar_image:
            uri_prefix: /images/avatar
            upload_destination: '%kernel.project_dir%/public/images/avatar'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        article_image:
            uri_prefix: /images/article
            upload_destination: '%kernel.project_dir%/public/images/article'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        produit_image:
            uri_prefix: /images/produit
            upload_destination: '%kernel.project_dir%/public/images/produit'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
