easy_admin:
    entities:
        Article:
            class: App\Entity\Article
            form:
                fields:
                    - {property: 'id'}
                    - {property: 'titre'}
                    - {property: 'contenu'}
                    - {property: 'auteur'}
                    - {property: 'image_name'}


