easy_admin:
    entities:
       Jeu:
            class: App\Entity\Jeu
            form:
                fields:
                    - {property: 'id'}
                    - {property: 'user_id'}
                    - {property: 'score'}